import { Config } from './config.model';

export const defaultConfig: Config = {
  octoprint: {
    url: 'http://192.168.31.13:5000/api/',
    accessToken: '6BF8CE4606204CF18CA90F3BE1A092EF',
  },
  printer: {
    name: '',
    xySpeed: 150,
    zSpeed: 5,
    zBabystepGCode: 'M290 Z',
    defaultTemperatureFanSpeed: {
      hotend: 200,
      heatbed: 60,
      fan: 100,
    },
  },
  filament: {
    thickness: 1.75,
    density: 1.25,
    feedLength: 0,
    feedSpeed: 20,
    feedSpeedSlow: 3,
    purgeDistance: 30,
    useM600: false,
  },
  plugins: {
    displayLayerProgress: {
      enabled: true,
    },
    enclosure: {
      enabled: false,
      ambientSensorID: null,
      filament1SensorID: null,
      filament2SensorID: null,
    },
    filamentManager: {
      enabled: true,
    },
    preheatButton: {
      enabled: true,
    },
    printTimeGenius: {
      enabled: true,
    },
    psuControl: {
      enabled: false,
      turnOnPSUWhenExitingSleep: false,
    },
    tpLinkSmartPlug: {
      enabled: false,
      smartPlugIP: '127.0.0.1',
    },
  },
  octodash: {
    customActions: [
      {
        icon: 'home',
        command: 'G28',
        color: '#70c13f',
        confirm: false,
        exit: false,
        label: '归零',
      },
      {
        icon: 'layer-group',
        command: 'QUAD_GANTRY_LEVEL',
        color: '#a5e397',
        confirm: true,
        exit: false,
        label: '门架调平',
      },
      {
        icon: 'sun',
        command: 'CASE_LED_ON',
        color: '#2c74e1',
        confirm: false,
        exit: false,
        label: '主灯开',
      },
      {
        icon: 'sun',
        command: 'CASE_LED_OFF',
        color: '#ababab',
        confirm: false,
        exit: false,
        label: '主灯关',
      },
      {
        icon: 'lightbulb',
        command: 'HOTEND_LED_ON',
        color: '#2c74e1',
        confirm: false,
        exit: false,
        label: '副灯开',
      },
      {
        icon: 'lightbulb',
        command: 'HOTEND_LED_OFF',
        color: '#ababab',
        confirm: false,
        exit: false,
        label: '副灯关',
      },
      {
        icon: 'stamp',
        command: 'CLEAN_NOZZLE',
        color: '#00ff1a',
        confirm: false,
        exit: false,
        label: '清洁喷头',
      },
      {
        icon: 'undo-alt',
        command: 'FIRMWARE_RESTART',
        color: '#e93232',
        confirm: true,
        exit: false,
        label: '重启系统',
      },
      {
        icon: 'chess-board',
        command: 'BED_MESH_CALIBRATE',
        color: '#e1b12c',
        confirm: true,
        exit: false,
        label: '网格调平',
      },
      {
        icon: 'ruler-vertical',
        command: 'Z_ENDSTOP_CALIBRATE',
        color: '#e1b12c',
        confirm: true,
        exit: false,
        label: 'Z轴高度',
      },
    ],
    fileSorting: {
      attribute: 'name',
      order: 'asc',
    },
    pollingInterval: 2000,
    touchscreen: true,
    turnScreenOffWhileSleeping: false,
    turnOnPrinterWhenExitingSleep: false,
    preferPreviewWhilePrinting: false,
    previewProgressCircle: false,
  },
};
